### ISSUE TITLE
All the problems I found by a quick look around

### ISSUE THREAD

**Issue by TymanWasTaken** [SkyBlockDev/malil-akairo#26]
1. You don't define the types of way too many things, mostly function parameters
2. You have the tsc settings to ignore implicit any and this, not very good practice
3. Please use consistent capitalization *please* (ClassName, variableName, FileName.ts)
4. You have way too many `any`s (1 is too many) please use `unknown` if you *really really* need to
5. Not really an issue but use https://npmjs.org/package/source-map-support
6. Some random files use .markdown file extension what
7. Those files also aren't in caps and thats weird
8. Missing a workflow
9. ~~Add dependabot~~
10. You appear to disable a bunch of types at the top of files which is not good, use // eslint-disable-next-line if you really really need to, though you shouldn't be disabling those checks anyway

**Comment by TymanWasTaken** [comment]
Oh yeah also
1. Some random files use .markdown file extension what
2. Those files also aren't in caps and thats weird
3. Missing a workflow
4. Add dependabot

**Comment by TymanWasTaken** [comment]
10. You appear to disable a bunch of types at the top of files which is not good, use `// eslint-disable-next-line` if you *really really* need to, though you shouldn't be disabling those checks anyway

**Comment by SkyBlockDev** [comment]
Fixed most of the issues
